export const FETCH_ALL_NAMESPACES_BEGIN = 'FETCH_ALL_NAMESPACES_BEGIN';
export const FETCH_ALL_NAMESPACES_SUCCESS = 'FETCH_ALL_NAMESPACES_SUCCESS';
export const FETCH_ALL_NAMESPACES_FAILURE = 'FETCH_ALL_NAMESPACES_FAILURE';
export const FETCH_NAMESPACE_BY_ID_BEGIN = 'FETCH_NAMESPACE_BY_ID_BEGIN';
export const FETCH_NAMESPACE_BY_ID_SUCCESS = 'FETCH_NAMESPACE_BY_ID_SUCCESS';
export const FETCH_NAMESPACE_BY_ID_FAILURE = 'FETCH_NAMESPACE_BY_ID_FAILURE';
export const FREE_NAMESPACE_ERRORS = 'FREE_NAMESPACE_ERRORS';
