export const FETCH_ALL_BY_LETTER_BEGIN = 'FETCH_ALL_BY_LETTER_BEGIN';
export const FETCH_ALL_BY_LETTER_SUCCESS = 'FETCH_ALL_BY_LETTER_SUCCESS';
export const FETCH_ALL_BY_LETTER_FAILURE = 'FETCH_ALL_BY_LETTER_FAILURE';
