inherit_mode:
  merge:
    - Exclude

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - client/**/*

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - bin/setup
    - bin/update

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  ExcludedMethods:
    - context
    - describe
    - feature
    - it
    - namespace
  Exclude:
    - db/schema.rb

Metrics/MethodLength:
  Max: 15
  ExcludedMethods:
    - change

Metrics/AbcSize:
  Max: 17
  Exclude:
    - db/migrate/*
